name: Build

on:
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100

    - name: dotnet build
      run: dotnet build --configuration Release

    - name: dotnet test
      run: dotnet test --no-build --configuration Release
